### ISSUE TITLE
Apex formatter issues: logical operators wrong formatted

### ISSUE THREAD

**Issue by micha-voigt** [JJLongoria/aura-helper#15]
Juan Jose, nice work!
while evaluating your VSCode extension I found one issue preventing me from using the Apex formatter all day. Logical operators like **&&** or **||** are formatted to  **& &** or **| |** with a blank between.

Btw. another small issue: **something + (something else)** is formatted to **something +(something else)**, where blank is missing between "**+(**".

If this would be fixed I would be very happy.

**Comment by JJLongoria** [comment]
Hi micha-voigt,
Thanks for report the issue, i know the first bug and i working on it but the second bug is new for me, i will work on it and publish the fixed version as soon as possible. If you see more bugs or have any suggestions, write me and I will do it as quickly as the time I have available allows me. (Sorry for my english)

**Comment by JJLongoria** [comment]
Bug fixed, version 1.5.2 published. Now formatter working fine.
