### ISSUE TITLE
Is there a way to configure the formatting feature?

### ISSUE THREAD

**Issue by joshua-nicholson** [JJLongoria/aura-helper#17]
The feature to format my Apex code is great since this seems to be the only one available. However, a mild annoyance is that it deletes the space in between an `if` and the open parenthesis. For example, `if (condition)` becomes `if(condition)`. This goes against my company code style so I would like to be able to configure this. Weirdly enough, it doesn't do this for `for` loops.

**Comment by JJLongoria** [comment]
Hi @joshua-nicholson 

Thank you for your suggestion and I am very grateful that the tool is useful to you. I am currently working on improvements to the code analyzer that will allow me to parameterize, among other things, the way in which the code is formatted, thus being able to adapt to the standards of any user. I hope to publish it as soon as possible taking into account the free time that I have after work :), I am sorry for any inconvenience it may cause you at the moment and if you have any other problems or suggestions I will be happy to analyze and implement as soon as posible :)

**Comment by JJLongoria** [comment]
Hi @joshua-nicholson 

As I told you, I would notify you when I had a version published with options to configure the Apex format. In the Aura Helper configuration, you will find the Apex Format section, where multiple options are included to choose how to format the code. I hope it is useful to you.
