### ISSUE TITLE
With latest version - formatting an apex code doesn't allow to enter blank lines

### ISSUE THREAD

**Issue by ronaksimar** [JJLongoria/aura-helper#19]

**Comment by JJLongoria** [comment]
I working on it, it's implemented and now I tested it. In the next realese you can choose if keep the blank lines, remove blank lines or select a maximum blank lines  (for example, if you configure 3 lines at maximum and have 8 blank lines in your code, the formatter reduce it to 3)

**Comment by JJLongoria** [comment]
Added in Aura Helper Format Config one option for keep new lines, or a maximum new lines
