### ISSUE TITLE
not able to format instanceof operator

### ISSUE THREAD

**Issue by SunilSaini2** [JJLongoria/aura-helper#21]
Hi,
 when i format code using aura-helper it is not able to format insteadof operator.
if i format bellow code
		    if (fieldName != null && !(fieldName instanceOf Map<String, Object>)){
than 		
  it's format like 
           if (fieldName != null && !(fieldNameinstanceOfMap<String, Object>)){

please suggest if there any configration is need to do to fix this.

**Comment by JJLongoria** [comment]
Hi @SunilSaini2. First, I apologize for reply you to late, sorry, I have to much work now. About the issue, I working on it for fix it and another bug. I expect publish this fixed quickly. Sorry for the problems that can cause to you this errors.

**Comment by JJLongoria** [comment]
New version published with this error fixed. Sorry for the delay. As good news, the new version comes loaded with improvements and optimizations.
