### ISSUE TITLE
Custom sObjects Invalid After Formatting

### ISSUE THREAD

**Issue by mcdowellkonnor** [JJLongoria/aura-helper#23]
I love this extension and use it frequently during my day-to-day coding. I've experienced a strange bug that interrupts my work, though. When we declare a custom sObject in the first line of a scope, and then format the document, the declaration syntax is messed up and the file cannot be saved. Here's an example:

```
private void BeforeFormat() {
     CustomObject__c exampleA = new CustomObject__c();
     CustomObject__c exampleB = new CustomObject__c();
}

private void AfterFormat() {
     CustomObject__cexampleA = new CustomObject__c(); // Notice the missing space
     CustomObject__c exampleB = new CustomObject__c(); // Space is still there in Line 2
}
```

Since this only impacts the very first line, I've had to use this workaround:
```
private void BeforeFormat() {
     // Some random comment will prevent formatting errors
     CustomObject__c exampleA = new CustomObject__c();
     CustomObject__c exampleB = new CustomObject__c();
}

private void AfterFormat() {
     // Some random comment will prevent formatting errors
     CustomObject__c exampleA = new CustomObject__c(); // Space is still there
     CustomObject__c exampleB = new CustomObject__c();
}
```

This issue also occurs in the first line of any compound statement. `for (...) { CustomObject__c example = new CustomObject__c(); }` will become `for (...) { CustomObject__cexample = new CustomObject__c(); }`

Since this impacts the entire document, it is difficult and annoying to fix manually and use comments to work-around in every instance. Is this a settings issue on my end or a bug that needs to be fixed? Any help is appreciated!

**Comment by JJLongoria** [comment]
Hi @mcdowellkonnor 
Thanks for report that bug. I try to resolve asap and publish a new fixed verion. Sorry for the problems and thanks again for report the bug and use the plugin. Im working too on a 2.0.0 version with to many changes and better performance.

**Comment by JJLongoria** [comment]
New version published with this error fixed. Sorry for the delay. As good news, the new version comes loaded with improvements and optimizations.
