### ISSUE TITLE
Refreshing Apex Classes Definitions keep loading

### ISSUE THREAD

**Issue by lz90** [JJLongoria/aura-helper#25]
After the update of vsCode and the aura-helper plugin, in the status bar has appeared this "refreshing apex classes definitions" that never stops. I've installed npm and the Aura-helper CLI, at the moment I use both ForceCode and SFDX.

![image](https://user-images.githubusercontent.com/42215530/87457168-3f2a5b80-c608-11ea-8bbd-333fb17b37e6.png)

**Comment by JJLongoria** [comment]
Thanks for  report the issue. I know it since yesterday and start working on it. I hope plublish a fixed version tomorrow :)

**Comment by JJLongoria** [comment]
New version publish with this error fixed.

**Comment by lz90** [comment]
Thank you for your wonderful project. 
Wish you the best.

**Comment by JJLongoria** [comment]
Sorry... I review it and publish a fix as soon as posible.

**Comment by JJLongoria** [comment]
Fixed the new problem with apex clases definitions refresh and published a new verison (v2.0.2). Sorry for this problems.
