### ISSUE TITLE
Refresh all SObject Definitions fails

### ISSUE THREAD

**Issue by davidwestberry** [JJLongoria/aura-helper#26]
SFDX: Refresh SObjects works with no problem. However, when I try to use AuraHelper: Refresh All SObject Definitions I get an undefined error.
![Screen Shot 2020-07-16 at 6 22 38 PM](https://user-images.githubusercontent.com/19600585/87732026-7ed07f00-c791-11ea-8925-3b3c3afe1734.png)

The output of Aura Helper console is simply
![Screen Shot 2020-07-16 at 6 24 48 PM](https://user-images.githubusercontent.com/19600585/87732112-b0e1e100-c791-11ea-8d74-7c616fdafb40.png)

**Comment by davidwestberry** [comment]
I think this might be due to the fact that I am using a macbook. It seems the AuraHelper CLI does not support mac

**Comment by JJLongoria** [comment]
Hello, and thanks for report. Actually Aura Helper CLI does not support max, but I working on it for add compatibility with linux and mac. Sorry.

**Comment by JJLongoria** [comment]
I have closed the issue by mistake. Sorry, the next version that I will publish will include support for linux and mac 👍

**Comment by JJLongoria** [comment]
hi  @davidwestberry now Aura Helper and Aura Helper CLI must be work on mac systems. I pubish a new version of both softwares. Aura Helper plugin updated automatically with VSCode but Aura Helper CLI must be  updated manually. Run "aura-helper update" or "npm install -g aura-helper-cli" for update the CLI. Thanks for report the issue and sorry for this problem ;)

**Comment by davidwestberry** [comment]
I appreciate you updating that so quickly. I was able to get the CLI and the extension updated to the latest versions. Now I am getting a new error
![Screen Shot 2020-07-17 at 11 35 49 AM](https://user-images.githubusercontent.com/19600585/87810049-fcdc6680-c821-11ea-9fd3-a13b896f5414.png)

**Comment by JJLongoria** [comment]
Thanks for report, sorry for the error, I dont have a mac system to test the app, only have linux and windows... I supuse that  work like other unix systems... I tried to fix it as son as posible and publish a new version. My apoligize and thanks again for report.

**Comment by davidwestberry** [comment]
If you need assistance debugging, I would be glad to assist. I'm just not sure how to debug VSCode extensions. If you need help, just let me know, but I will need a tutorial on how to debug the extension.

**Comment by JJLongoria** [comment]
Thanks for your offer, i porpuse you other easy option. I send to you to your email a VSIX for install from vscode and not from the extension market. When the VSIX does not fail i publish a final version on marketplace. If you are interested write an email to juanjoselongoria@gmail.com is my email and not need to publish here your email for privacy ;)

**Comment by JJLongoria** [comment]
Hi  @davidwestberry 

Finally, I install  a  Mac OS on a VMWare for test the app and fix all mac errors. Now Aura Helper and Aura Helper CLI have full compatibility with  Windows,  Linux  and Max systems. Enjoy it! 👍 

Regards!

**Comment by davidwestberry** [comment]
Thank you so much for your help with that. I'm sorry I wasn't able to
assist more in debugging, I just am not sure how to debug an extension. I
will update to the latest version and try it out.
