### ISSUE TITLE
space  still be removed

### ISSUE THREAD

**Issue by akira1987** [JJLongoria/aura-helper#27]
Apex variable declaration When formatting, the variable and the space in the middle will be removed
`EmailTemplate validEmailTemplate = new EmailTemplate();`
fomatted
`EmailTemplatevalidEmailTemplate = new EmailTemplate();`

**Comment by JJLongoria** [comment]
Hi @akira1987 , thanks for report this issue. Im working on it now and publish a fexed version as soon as posible. Sorry for the problems.

**Comment by JJLongoria** [comment]
Hi @akira1987 I published a new v2.1.0 version with this bug fixed and some new features.
