### ISSUE TITLE
No longer working for VSCode?

### ISSUE THREAD

**Issue by TheMadPope** [JJLongoria/aura-helper#29]
Aura-helper no longer shows up when I start a comment block with /** . Entering command AuraHelper: Edit Apex Comment Template shows error "An error occurred while processing command. Error: TypeError: str.split is not a function" and doesn't do anything. Not sure what I'm missing...

**Comment by JJLongoria** [comment]
Hi @TheMadPope , thanks for report.

Don't worry, Aura Helper still working on VSCode and I continue the maintenance. Recently a publish the v2.0.0 version with too many changes on existing features for improve it and new features, and now im working to add compatibility with Mac (now have linux and windows compatibility). 

Sorry for this problem, but dont worry, it`s only a bug and Aura Helper is still alive 👍 I will working on this bug and publish the new fixed version as soon as posible.

Regards!

**Comment by TheMadPope** [comment]
Thanks, I should have mentioned, I am on a Mac. Thanks! Love this extension!

**Comment by JJLongoria** [comment]
Hi! @TheMadPope 

I published a  new version  for Aura Helper and  Aura Helper CLI to improve compatibility with Mac systems (and other features and fixes), also fix the bugs with autocompletion on apex comments 👍  

Regards!
