### ISSUE TITLE
Line breaks were made even where they were not required

### ISSUE THREAD

**Issue by akira1987** [JJLongoria/aura-helper#30]
Before Format
public Attachment attachment1 {get;set;}

Wanna to Format
public Attachment attachment1 { get; set; }

After Formated
public Attachment attachment1 { 
 get;
 set; 
}

**Comment by JJLongoria** [comment]
Hi @akira1987 , thanks for report!

I working on some bug fixeds and I will include this issue. Sorry for the problems and I will publish a new bug fixed version as soon as posible.

Regards!

**Comment by JJLongoria** [comment]
Hi  @akira1987 

I published  a new version (v2.2.0) with some improvements and a new setting for Apex Formatter to formar empty properties on a  single line 👍 You can  found it on Settings > Aura Helper > Apex Format > Class Members > Single Line Properties

Regards!
