### ISSUE TITLE
Lines between methods and class attributes removed

### ISSUE THREAD

**Issue by fanch-ragon** [JJLongoria/aura-helper#41]
Hello, sorry to interrupt again.

Since last version I noticed that lines between methods and/or class attributes are removed, regardless of the newLinesBetweenCodeBlockMembers setting.
Is this a behavior you can replicate on your side as well?
For instance, if I format this code:
```
public class TestClass {

	static boolean bool1 = false;



	static boolean bool2 = true;

	
	public static void test1(String test1) {
	}
	
	public static void test2(String test2) {
	}
}
```
I will get this result, despite newLinesBetweenCodeBlockMembers = 1 :
```
public class TestClass {
	static boolean bool1 = false;
	static boolean bool2 = true;
	public static void test1(String test1) {
	}
	public static void test2(String test2) {
	}
}
```
I would more have expected this result, if I am not wrong?
```
public class TestClass {
	static boolean bool1 = false;

	static boolean bool2 = true;

	public static void test1(String test1) {
	}

	@AuraEnabled
	public static void test2(String test2) {
	}
}
```

**Comment by JJLongoria** [comment]
hi @fanch-ragon 

Indeed, it is an unexpected behavior of the formatting option you mentioned. I just publish a new fix version that fixes the problem. Sorry for the delay in answering, these dates, the family, the holidays ... you know.

PD: Not apologize to help me to improve Aura Helper, your reports are valius to found errors or unexpected behaviours like this.

Enjoy it!
Regards.

**Comment by fanch-ragon** [comment]
No issue, thanks for the quick fix once again :)

Regards
