### ISSUE TITLE
Trigger - space before 'on' keyword gets removed

### ISSUE THREAD

**Issue by elp92** [JJLongoria/aura-helper#45]
Hi there, a little issue I ran into.

My current triggers look like this:

![image](https://user-images.githubusercontent.com/17134445/171731665-a23a1f33-051b-467b-a0a0-fc39b3afbad7.png)

However when I run the formatter it turns into this:

![image](https://user-images.githubusercontent.com/17134445/171731888-030fd3e9-1058-48dc-9672-3150ef1dfda2.png)

Looks like the space before the 'on' keyword just gets removed, and I've tried a lot of combinations from the extension config.

**Comment by JJLongoria** [comment]
Hi @elp92 Thanks for report the bug, I try to fix it as soon as posible.I'm sorry for the problems that may cause you, I hope to solve it soon.

Thanks and regards!

**Comment by JJLongoria** [comment]
Hello @elp92 I published now a new fix version (4.2.1) to fix this error,

Sorry for the problems and enjoy Aura Helper!

Regards.
