### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vjerome2** [JJLongoria/aura-helper#46]
- Issue Type: `Performance`
- Extension Name: `aura-helper`
- Extension Version: `4.2.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/vlettau/AppData/Local/Temp/Kanko.aura-helper-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JJLongoria** [comment]
I finally resolve this problem with the last update.
