### ISSUE TITLE
Formatting issue - Unclear problem

### ISSUE THREAD

**Issue by ugurcanerkal** [JJLongoria/aura-helper#49]
Hi, 

We were able to format the document like this before:
![image](https://user-images.githubusercontent.com/78914382/215356417-2f353508-bebb-4947-b3c4-8d46053b0819.png)

But now, if I format the document, the result is like this. I'm not sure how to describe the issue here but 
![image](https://user-images.githubusercontent.com/78914382/215356478-3e81060f-fbe9-4fe8-8179-756aaba86c02.png)

**Comment by JJLongoria** [comment]
Hi @ugurcanerkal 

I'm sorry for the delay in my response. I develop Aura Helper in my free time and for months I have barely had a little time to analyze and solve the problems.

I have been trying to reproduce the error in some way for several days and I am not able to. In all the situations that I have tried, the formatting is done correctly...

Could you give me the configuration you have for the Aura Helper formatter?

Thank you and sorry for the inconvenience.
